Fix/improve cities average salaries
The-Cupcake-team/cost-of-living pull request #22
Opened 2023-02-17 21:31 UTC by Ali873-debug

finished my task

2023-02-17 21:38 UTC, Mohammedbih requested changes

2023-02-17 21:38 UTC, Mohammedbih commented on src/test/kotlin/interactor/GetCitiesAverageSalaryTest.kt
> +    fun should_EmptyList_when_EnteringEmptyList() {
should_ThrowException

2023-02-18 09:09 UTC, Mohammedbih submitted a review, later dismissed

2023-02-18 18:19 UTC, Mohammedbih approved these changes

2023-02-19 18:28 UTC, AmeerAmjed requested changes
change pull request to develop

2023-02-20 13:01 UTC, closed without merging