Fix/refactor feature‏ city has the highest difference
The-Cupcake-team/cost-of-living pull request #23
Opened 2023-02-17 21:53 UTC by Ethaar7

2023-02-18 09:12 UTC, Mohammedbih requested changes

2023-02-18 09:12 UTC, Mohammedbih commented on src/test/kotlin/interactor/GetCostlierCityInteractorTest.kt
> +    fun should_ReturnCorrectCity_When_TheDataIsInValid() {
should throw exception

2023-02-18 18:17 UTC, Mohammedbih approved these changes

2023-02-18 18:29 UTC, Mohammedbih approved these changes

2023-02-19 11:21 UTC, TarekIdrees approved these changes

2023-02-19 11:50 UTC, Sajadio approved these changes
good work

2023-02-19 18:37 UTC, closed without merging