fix/top_cities_has_cheapest_price_of_apartments_and_year
The-Cupcake-team/cost-of-living pull request #25
Opened 2023-02-18 18:58 UTC by khaledeid1k

ameer don't touch my code ,

2023-02-19 20:28 UTC, AmeerAmjed requested changes

2023-02-19 20:28 UTC, AmeerAmjed commented on src/test/kotlin/interactor/GetTopCitiesHasCheapestPriceOfApartmentsAndCountOfYearToBuyTest.kt
> +            listOf(
put expected value  in variable

2023-02-19 20:28 UTC, AmeerAmjed commented on src/main/kotlin/interactor/GetTopCitiesHasCheapestPriceOfApartmentsAndYearInteractor.kt
> +            ?: throw Exception("Invalid Data")
The message is not clear "Invalid Data"

2023-02-20 14:33 UTC, khaledeid1k commented on src/main/kotlin/interactor/GetTopCitiesHasCheapestPriceOfApartmentsAndYearInteractor.kt
> +            ?: throw Exception("Invalid Data")
what your suggestion to name it

2023-02-20 20:07 UTC, mustafa-sab3alarab requested changes

2023-02-20 20:07 UTC, mustafa-sab3alarab commented on src/test/kotlin/interactor/GetTopCitiesHasCheapestPriceOfApartmentsAndCountOfYearToBuyTest.kt
> +        emptyDataSource = EmptyFakeData()
change this class to object

2023-02-20 20:17 UTC, mustafa-sab3alarab approved these changes

2023-02-20 20:18 UTC, AmeerAmjed approved these changes

2023-02-20 20:22 UTC, merged