Feature/cheapest city internet
The-Cupcake-team/cost-of-living pull request #3
Opened 2023-02-10 21:39 UTC by davios21

2023-02-11 12:26 UTC, AmeerAmjed requested changes
Good work David, apply change.

2023-02-11 12:26 UTC, AmeerAmjed commented on src/main/kotlin/interactor/GetCityHasCheapestInternetConnectionInteractor.kt
> +    fun execute(cities:List<CityEntity>): CityEntity?
In my opinion, it's not a good idea to use a "compact function" with multi-line function content, as it may require additional changes in the future if modifications need to be made. Furthermore, this function is not easily readable.

2023-02-11 12:26 UTC, AmeerAmjed commented on build.gradle.kts
> +    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
Why???

2023-02-11 12:26 UTC, AmeerAmjed commented on build.gradle.kts
> +    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
Why???

2023-02-11 12:26 UTC, AmeerAmjed commented on src/test/kotlin/interactor/GetCityHasCheapestInternetConnectionInteractorTest.kt
> +    fun should_ReturnNull_WhenCityEntity_IsEmpty(){
rename to **should_ReturnNull_WhenCityEntityEmpty**

2023-02-11 21:07 UTC, mosayed01 commented on src/main/kotlin/interactor/GetCityHasCheapestInternetConnectionInteractor.kt
> +             }[0]
you can use `.first()` here

2023-02-12 05:13 UTC, Mohammedbih approved these changes, later dismissed

2023-02-12 16:14 UTC, AmeerAmjed approved these changes, later dismissed

2023-02-12 18:26 UTC, TarekIdrees submitted a review, later dismissed

2023-02-12 18:35 UTC, Mohammedbih approved these changes, later dismissed

2023-02-13 11:45 UTC, merged