new feature
The-Cupcake-team/cost-of-living pull request #33
Opened 2023-02-20 23:32 UTC by MohamedEmadEldeenAboud

Yoge is addicted to soft drinks. He is looking for the best 3 cities. He can save a lot of money to buy soft drinks. He does not spend a lot of money on eating and drinking it. $500 is enough and more. He does not need luxurious housing. Anything that suffices. yoge takes the average salary of the city

2023-02-20 23:47 UTC, Mohammedbih requested changes

2023-02-20 23:47 UTC, Mohammedbih commented on src/test/kotlin/interactor/GetBest3CitiesForBuyingSoftDrinksInteractorTest.kt
> +        fakeData.changeDataSource(TestCase.BestCityForSavingMoney)
Move to singleton style!

2023-02-20 23:47 UTC, Mohammedbih commented on src/test/kotlin/interactor/GetBest3CitiesForBuyingSoftDrinksInteractorTest.kt
> +    fun should_ReturnTrue_When_TheCityHasNotNullRequireValues() {
move to ` fun `should return true when the city has not null require values`()` style.

2023-02-20 23:47 UTC, Mohammedbih commented on src/test/kotlin/interactor/GetBestCityForSavingMoneyInteractorTest.kt
>          Assertions.assertTrue(result)
assertTrue(result) *

2023-02-21 01:34 UTC, Mohammedbih approved these changes

2023-02-21 07:35 UTC, AmeerAmjed approved these changes

2023-02-21 10:51 UTC, closed without merging