feature of (Average Fruit And Vegetables) done.
The-Cupcake-team/cost-of-living pull request #4
Opened 2023-02-11 22:11 UTC by mustafa-sab3alarab

2023-02-11 23:25 UTC, AmeerAmjed requested changes

2023-02-11 23:25 UTC, AmeerAmjed commented on src/main/kotlin/interactor/GetAverageFruitAndVegetablesInteractor.kt
> +            .sortedBy { it.fruitAndVegetablesPrices.getAverageFruitVegetablesPrice() / it.averageMonthlyNetSalaryAfterTax!! }
Relocate this function from its current position to an external function, and modify the "/" operator to utilize the **div()** function instead.

2023-02-11 23:25 UTC, AmeerAmjed commented on src/test/kotlin/interactor/GetAverageFruitAndVegetablesInteractorTest.kt
> +class GetAverageFruitAndVegetablesInteractorTest {
you need more test case "one not enough" 
one case 
1. return empty list if all cities have no average salary.
try add more

2023-02-12 05:11 UTC, Mohammedbih requested changes
Nice work 
Just look at reviews required

2023-02-12 05:11 UTC, Mohammedbih commented on src/main/kotlin/interactor/GetAverageFruitAndVegetablesInteractor.kt
> +        return with(this) {
Here you don't need with keyword

2023-02-12 05:11 UTC, Mohammedbih commented on src/main/kotlin/interactor/GetAverageFruitAndVegetablesInteractor.kt
> +        return with(this) {
Because your scope in this time already **this**

2023-02-12 09:26 UTC, AmeerAmjed requested changes

2023-02-12 09:26 UTC, AmeerAmjed commented on src/test/kotlin/interactor/GetAverageFruitAndVegetablesInteractorTest.kt
> +    fun should_ReturnListOf10CitiesNames_When_TheDataSourceIsValid() {
you should use style **(given , when, then)** and write description

2023-02-12 11:58 UTC, closed without merging