CitiesAverageSalary finished
The-Cupcake-team/cost-of-living pull request #5
Opened 2023-02-12 11:40 UTC by Ali873-debug

complete the execute function for cities average salary, and add fake data, fix some test casese

2023-02-12 12:29 UTC, Mohammedbih requested changes

2023-02-12 12:29 UTC, Mohammedbih commented on src/test/kotlin/interactor/GetCitiesAverageSalaryTest.kt
>          assertThrows(Exception::class.java,result)
You can use Same type of exception.

2023-02-12 12:39 UTC, Mohammedbih approved these changes, later dismissed

2023-02-13 11:54 UTC, AmeerAmjed submitted a review, later dismissed

2023-02-13 12:31 UTC, Mohammedbih approved these changes, later dismissed

2023-02-13 20:28 UTC, AmeerAmjed approved these changes, later dismissed

2023-02-13 20:34 UTC, merged